### ISSUE TITLE
Implementierung des Modellkatalogs und der Suchfunktion

### ISSUE THREAD

**Issue by Kubisili** [ReinerMx/GS2-2024#7]
Ein durchsuchbarer, filterbarer Katalog für ML-Modelle basierend auf der STAC-MLM-Erweiterung. Inklusive Suchfunktion und Filteroptionen für Modellaufgaben, geografische Regionen, Datentypen, Zeiträume und Wolkenabdeckung.

**Comment by amlusc** [comment]
erledigt
